[project]
name = "bsky-scrape"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=24.10.0",
    "duckdb>=1.1.3",
    "pyarrow>=18.0.0",
    "typer>=0.13.0",
]
